### ISSUE TITLE
Change repository name and split it

### ISSUE THREAD

**Issue by micdenny** [micdenny/docker-samples#10]
I think this repo has taken flight ✈️ at least for rabbitmq, but redis is not joking as well:

![image](https://user-images.githubusercontent.com/1633595/186228079-607af5fb-4bbf-49c7-87cd-f7222b01089a.png)

![image](https://user-images.githubusercontent.com/1633595/186228116-15ca594b-e212-47a8-8ca6-317344cc1881.png)

So I think it should be better to rename this repo, probably also split in two different repo, one for rabbitmq and another one for redis.

**Comment by nithinmohantk** [comment]
You could create two github repos called 

- rabbitmq-windows
- redis-windows 

Then move the code in to respective repos. Can help with it as well, once the repos are created.

**Comment by micdenny** [comment]
done 😄 

- https://github.com/micdenny/rabbitmq-windows
- https://github.com/micdenny/redis-windows
