### ISSUE TITLE
Push docker hub overview from repo README.md

### ISSUE THREAD

**Issue by micdenny** [micdenny/docker-samples#8]
After adding the new build and push system using actions, we lost the automatic pushing of the repo readme.md on the overview page of docker hub, before this was accomplished from the built-in docker hub build system and I would like to restore it.

**Comment by micdenny** [comment]
@nithinmohantk can you help on this?

**Comment by micdenny** [comment]
in the meanwhile I manually synch it

**Comment by nithinmohantk** [comment]
@micdenny  README.md while using Dockerhub builds were easier to push. Need to figure out API way of pushing it, if using github actions. 
I will explore around options.
